### PR TITLE
Add reloadInterval option to type definitions

### PR DESCRIPTION
**Pull request by pedrodurek**
Fix: https://github.com/i18next/i18next-http-backend/issues/59

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
probably `false | number` is better?

**Comment by pedrodurek** [comment]
ohhh, so it's not just a boolean, it also accepts number values, is that it? Does it also accept true (that defaults to something)?

**Comment by adrai** [comment]
Just checked, it's  exactly like here: https://github.com/locize/i18next-locize-backend/blob/master/index.d.ts#L63 ;-)

**Comment by pedrodurek** [comment]
Fixed!

**Comment by adrai** [comment]
thx

**Pull request merged**
